// =============================================================================
// SSJS Catalog Test — AUTO-GENERATED by ssjs-data/scripts/audit-method-coverage.mjs
// Every method/function catalogued in ssjs-data. Use for hover, completion, and
// TypeScript (ssjs-ts) validation in vscode-sfmc-language / sfmc-language-lsp.
// Regenerate: cd ssjs-data && node scripts/audit-method-coverage.mjs
// =============================================================================

Platform.Load("core", "1.1.5");

// ── Shared instance stubs (not executed — syntax/IntelliSense validation only) ──
var _wsproxy = new Script.Util.WSProxy();
var _httpReq = new Script.Util.HttpRequest("https://example.com");
var _de = DataExtension.Init("TestDE");
var _account = Account.Init("");
var _accountUser = AccountUser.Init("", 1);
var _portfolio = Portfolio.Init("");
var _contentArea = ContentAreaObj.Init("");
var _folder = Folder.Init("");
var _template = Template.Init("");
var _deliveryProfile = DeliveryProfile.Init("");
var _senderProfile = SenderProfile.Init("");
var _sendClass = SendClassification.Init("");
var _filterDef = FilterDefinition.Init("");
var _queryDef = QueryDefinition.Init("");
var _list = List.Init("");
var _listSubscribers = _list.Subscribers;
var _listSubTracking = _listSubscribers.Tracking;
var _subscriber = Subscriber.Init("");
var _subscriberAttrs = _subscriber.Attributes;
var _subscriberLists = _subscriber.Lists;
var _email = Email.Init("");
var _send = Send.Init(1);
var _sendDef = Send.Definition.Init("");
var _sendTracking = _send.Tracking;
var _triggeredSend = TriggeredSend.Init("");
var _tsTracking = _triggeredSend.Tracking;
var _tsClicks = _tsTracking.Clicks;
var _tsInterval = _tsTracking.TotalByInterval;
var _arr = [1, 2, 3];
var _str = "test";
var _num = 42;
var _obj = {};
var _re = /test/i;
var _date = new Date();


// ── Platform ──
// Platform.Load
void (Platform.Load("libraryName", "version"));

// ── Platform.Function ──
// Platform.Function.Lookup
void (Platform.Function.Lookup("deName", "returnField", [], []));
// Platform.Function.LookupRows
void (Platform.Function.LookupRows("deName", [], []));
// Platform.Function.LookupOrderedRows
void (Platform.Function.LookupOrderedRows("deName", 1, "orderBy", [], []));
// Platform.Function.InsertData
void (Platform.Function.InsertData("deName", [], []));
// Platform.Function.InsertDE
void (Platform.Function.InsertDE("deName", [], []));
// Platform.Function.UpdateData
void (Platform.Function.UpdateData("deName", [], [], [], []));
// Platform.Function.UpdateDE
void (Platform.Function.UpdateDE("deName", [], [], [], []));
// Platform.Function.UpsertData
void (Platform.Function.UpsertData("deName", [], [], [], []));
// Platform.Function.UpsertDE
void (Platform.Function.UpsertDE("deName", [], [], [], []));
// Platform.Function.DeleteData
void (Platform.Function.DeleteData("deName", [], []));
// Platform.Function.DeleteDE
void (Platform.Function.DeleteDE("deName", [], []));
// Platform.Function.ContentBlockByKey
void (Platform.Function.ContentBlockByKey("customerKey"));
// Platform.Function.ContentBlockByName
void (Platform.Function.ContentBlockByName("name"));
// Platform.Function.ContentBlockByID
void (Platform.Function.ContentBlockByID(1));
// Platform.Function.ContentImageByKey
void (Platform.Function.ContentImageByKey("key"));
// Platform.Function.ContentImageByID
void (Platform.Function.ContentImageByID(1));
// Platform.Function.TreatAsContent
void (Platform.Function.TreatAsContent("content"));
// Platform.Function.BeginImpressionRegion
void (Platform.Function.BeginImpressionRegion("name"));
// Platform.Function.EndImpressionRegion
void (Platform.Function.EndImpressionRegion());
// Platform.Function.Now
void (Platform.Function.Now());
// Platform.Function.SystemDateToLocalDate
void (Platform.Function.SystemDateToLocalDate("dateString"));
// Platform.Function.LocalDateToSystemDate
void (Platform.Function.LocalDateToSystemDate("dateString"));
// Platform.Function.RaiseError
void (Platform.Function.RaiseError("message"));
// Platform.Function.GUID
void (Platform.Function.GUID());
// Platform.Function.IsEmailAddress
void (Platform.Function.IsEmailAddress("value"));
// Platform.Function.IsPhoneNumber
void (Platform.Function.IsPhoneNumber("value"));
// Platform.Function.CreateObject
void (Platform.Function.CreateObject("objectType"));
// Platform.Function.SetObjectProperty
void (Platform.Function.SetObjectProperty({}, "propertyName", {}));
// Platform.Function.AddObjectArrayItem
void (Platform.Function.AddObjectArrayItem({}, "propertyName", {}));
// Platform.Function.InvokeCreate
void (Platform.Function.InvokeCreate({}, [], {}));
// Platform.Function.InvokeUpdate
void (Platform.Function.InvokeUpdate({}, [], {}));
// Platform.Function.InvokeDelete
void (Platform.Function.InvokeDelete({}, [], {}));
// Platform.Function.InvokeRetrieve
void (Platform.Function.InvokeRetrieve({}, []));
// Platform.Function.InvokePerform
void (Platform.Function.InvokePerform({}, "method", [], {}));
// Platform.Function.InvokeConfigure
void (Platform.Function.InvokeConfigure({}, "method", [], {}));
// Platform.Function.InvokeExecute
void (Platform.Function.InvokeExecute({}, []));
// Platform.Function.InvokeExtract
void (Platform.Function.InvokeExtract({}, []));
// Platform.Function.InvokeSchedule
void (Platform.Function.InvokeSchedule({}, "action", {}, []));
// Platform.Function.HTTPGet
void (Platform.Function.HTTPGet("url"));
// Platform.Function.HTTPPost
void (Platform.Function.HTTPPost("url", "contentType", "payload"));
// Platform.Function.ParseJSON
void (Platform.Function.ParseJSON("jsonString"));
// Platform.Function.RedirectTo
void (Platform.Function.RedirectTo("url"));
// Platform.Function.UrlEncode
void (Platform.Function.UrlEncode("url"));
// Platform.Function.Base64Encode
void (Platform.Function.Base64Encode("string"));
// Platform.Function.Base64Decode
void (Platform.Function.Base64Decode("encodedString"));
// Platform.Function.MD5
void (Platform.Function.MD5("string"));
// Platform.Function.Stringify
void (Platform.Function.Stringify({}));
// Platform.Function.ContentArea
void (Platform.Function.ContentArea(1));
// Platform.Function.ContentAreaByName
void (Platform.Function.ContentAreaByName("name"));
// Platform.Function.IsCHTMLBrowser
void (Platform.Function.IsCHTMLBrowser("userAgentString"));

// ── Platform.Variable ──
// Platform.Variable.GetValue
void (Platform.Variable.GetValue("variableName"));
// Platform.Variable.SetValue
void (Platform.Variable.SetValue("variableName", "value"));

// ── Platform.Response ──
// Platform.Response.SetResponseHeader
void (Platform.Response.SetResponseHeader("headerName", "value"));
// Platform.Response.RemoveResponseHeader
void (Platform.Response.RemoveResponseHeader("headerName"));
// Platform.Response.Redirect
void (Platform.Response.Redirect("url", true));
// Platform.Response.SetCookie
void (Platform.Response.SetCookie("name", "value"));
// Platform.Response.RemoveCookie
void (Platform.Response.RemoveCookie("name"));
// Platform.Response.Write
void (Platform.Response.Write("content"));
// Platform.Response.ContentType
void (Platform.Response.ContentType);
// Platform.Response.CharacterSet
void (Platform.Response.CharacterSet);

// ── Platform.Request ──
// Platform.Request.GetQueryStringParameter
void (Platform.Request.GetQueryStringParameter("parameterName"));
// Platform.Request.GetFormField
void (Platform.Request.GetFormField("name"));
// Platform.Request.GetPostData
void (Platform.Request.GetPostData());
// Platform.Request.GetCookieValue
void (Platform.Request.GetCookieValue("cookieName"));
// Platform.Request.GetUserLanguages
void (Platform.Request.GetUserLanguages());
// Platform.Request.GetRequestHeader
void (Platform.Request.GetRequestHeader("headerName"));
// Platform.Request.Browser
void (Platform.Request.Browser);
// Platform.Request.ClientIP
void (Platform.Request.ClientIP);
// Platform.Request.HasSSL
void (Platform.Request.HasSSL);
// Platform.Request.IsSSL
void (Platform.Request.IsSSL);
// Platform.Request.Method
void (Platform.Request.Method);
// Platform.Request.QueryString
void (Platform.Request.QueryString);
// Platform.Request.ReferrerURL
void (Platform.Request.ReferrerURL);
// Platform.Request.RequestURL
void (Platform.Request.RequestURL);
// Platform.Request.UserAgent
void (Platform.Request.UserAgent);

// ── Platform.Recipient ──
// Platform.Recipient.GetAttributeValue
void (Platform.Recipient.GetAttributeValue("attributeName"));

// ── HTTPHeader ──
// HTTPHeader.GetValue
void (HTTPHeader.GetValue("name"));
// HTTPHeader.SetValue
void (HTTPHeader.SetValue("name", "value"));
// HTTPHeader.Remove
void (HTTPHeader.Remove("headerName"));

// ── Attribute ──
// Attribute.GetValue
void (Attribute.GetValue("name"));

// ── DateTime ──
// DateTime.SystemDateToLocalDate
void (DateTime.SystemDateToLocalDate("dateString"));
// DateTime.LocalDateToSystemDate
void (DateTime.LocalDateToSystemDate("dateString"));

// ── DateTime.TimeZone ──
// DateTime.TimeZone.Retrieve
void (DateTime.TimeZone.Retrieve({}));

// ── ErrorUtil ──
// ErrorUtil.ThrowWSProxyError
void (ErrorUtil.ThrowWSProxyError({}));

// ── HTTP ──
// HTTP.Get
void (HTTP.Get("url"));
// HTTP.Post
void (HTTP.Post("url", "contentType", "payload"));

// ── Script.Util ──
// new Script.Util.WSProxy
void (new Script.Util.WSProxy());
// new Script.Util.HttpRequest
void (new Script.Util.HttpRequest("url"));
// new Script.Util.HttpGet
void (new Script.Util.HttpGet("url"));

// ── WSProxy ──
// <WSProxyInstance>.createItem
void (_wsproxy.createItem("objectType", {}));
// <WSProxyInstance>.updateItem
void (_wsproxy.updateItem("objectType", {}));
// <WSProxyInstance>.deleteItem
void (_wsproxy.deleteItem("objectType", {}));
// <WSProxyInstance>.retrieve
void (_wsproxy.retrieve("objectType", []));
// <WSProxyInstance>.getNextBatch
void (_wsproxy.getNextBatch("objectType", "requestId"));
// <WSProxyInstance>.performItem
void (_wsproxy.performItem("objectType", {}, "action"));
// <WSProxyInstance>.performBatch
void (_wsproxy.performBatch("objectType", [], "action"));
// <WSProxyInstance>.describe
void (_wsproxy.describe([]));
// <WSProxyInstance>.execute
void (_wsproxy.execute([], "requestName"));
// <WSProxyInstance>.setClientId
void (_wsproxy.setClientId({}));
// <WSProxyInstance>.resetClientIds
void (_wsproxy.resetClientIds());
// <WSProxyInstance>.createBatch
void (_wsproxy.createBatch("objectType", []));
// <WSProxyInstance>.updateBatch
void (_wsproxy.updateBatch("objectType", []));
// <WSProxyInstance>.deleteBatch
void (_wsproxy.deleteBatch("objectType", []));

// ── Script.Util.HttpRequest ──
// <HttpRequestInstance>.send
void (_httpReq.send());
// <HttpRequestInstance>.setHeader
void (_httpReq.setHeader("name", "value"));
// <HttpRequestInstance>.clearHeaders
void (_httpReq.clearHeaders());
// <HttpRequestInstance>.removeHeader
void (_httpReq.removeHeader("name"));

// ── Core Library ──
// DataExtension.Init
void (DataExtension.Init("key"));
// DataExtension.Add
void (DataExtension.Add({}));
// DataExtension.Retrieve
void (DataExtension.Retrieve({}));
// DataExtension.Fields.Add
void (_de.Fields.Add({}));
// DataExtension.Fields.Retrieve
void (_de.Fields.Retrieve());
// DataExtension.Fields.UpdateSendableField
void (_de.Fields.UpdateSendableField("deFieldName", "subscriberField"));
// DataExtension.Rows.Add
void (_de.Rows.Add([]));
// DataExtension.Rows.Lookup
void (_de.Rows.Lookup([], []));
// DataExtension.Rows.Remove
void (_de.Rows.Remove([], []));
// DataExtension.Rows.Retrieve
void (_de.Rows.Retrieve());
// DataExtension.Rows.Update
void (_de.Rows.Update({}, [], []));
// Account.Init
void (Account.Init("key"));
// Account.Retrieve
void (Account.Retrieve({}));
// Account.Update
void (_account.Update({}));
// Account.Tracking.Retrieve
void (Account.Tracking.Retrieve({}));
// AccountUser.Init
void (AccountUser.Init("targetUserKey", 1));
// AccountUser.Add
void (AccountUser.Add({}));
// AccountUser.Retrieve
void (AccountUser.Retrieve({}));
// AccountUser.Update
void (_accountUser.Update({}));
// AccountUser.Activate
void (_accountUser.Activate());
// AccountUser.Deactivate
void (_accountUser.Deactivate());
// Portfolio.Init
void (Portfolio.Init("key"));
// Portfolio.Add
void (Portfolio.Add({}));
// Portfolio.Retrieve
void (Portfolio.Retrieve({}));
// Portfolio.Update
void (_portfolio.Update({}));
// Portfolio.Remove
void (_portfolio.Remove());
// ContentAreaObj.Init
void (ContentAreaObj.Init("key"));
// ContentAreaObj.Add
void (ContentAreaObj.Add({}));
// ContentAreaObj.Retrieve
void (ContentAreaObj.Retrieve({}));
// ContentAreaObj.Update
void (_contentArea.Update({}));
// ContentAreaObj.Remove
void (_contentArea.Remove());
// Folder.Init
void (Folder.Init());
// Folder.Add
void (Folder.Add({}));
// Folder.Retrieve
void (Folder.Retrieve({}));
// Folder.Update
void (_folder.Update({}));
// Folder.Remove
void (_folder.Remove());
// Folder.SetID
void (_folder.SetID(1));
// Template.Init
void (Template.Init("key"));
// Template.Add
void (Template.Add({}));
// Template.Retrieve
void (Template.Retrieve({}));
// Template.Update
void (_template.Update({}));
// DeliveryProfile.Init
void (DeliveryProfile.Init("key"));
// DeliveryProfile.Add
void (DeliveryProfile.Add({}));
// DeliveryProfile.Update
void (_deliveryProfile.Update({}));
// DeliveryProfile.Remove
void (_deliveryProfile.Remove());
// SenderProfile.Init
void (SenderProfile.Init("key"));
// SenderProfile.Add
void (SenderProfile.Add({}));
// SenderProfile.Update
void (_senderProfile.Update({}));
// SenderProfile.Remove
void (_senderProfile.Remove());
// SendClassification.Init
void (SendClassification.Init("key"));
// SendClassification.Add
void (SendClassification.Add({}));
// SendClassification.Retrieve
void (SendClassification.Retrieve({}));
// SendClassification.Update
void (_sendClass.Update({}));
// SendClassification.Remove
void (_sendClass.Remove());
// FilterDefinition.Init
void (FilterDefinition.Init("key"));
// FilterDefinition.Add
void (FilterDefinition.Add({}));
// FilterDefinition.Retrieve
void (FilterDefinition.Retrieve({}));
// FilterDefinition.Update
void (_filterDef.Update({}));
// FilterDefinition.Remove
void (_filterDef.Remove());
// QueryDefinition.Init
void (QueryDefinition.Init("key"));
// QueryDefinition.Add
void (QueryDefinition.Add({}));
// QueryDefinition.Retrieve
void (QueryDefinition.Retrieve({}));
// QueryDefinition.Update
void (_queryDef.Update({}));
// QueryDefinition.Remove
void (_queryDef.Remove());
// QueryDefinition.Perform
void (_queryDef.Perform("action"));
// List.Init
void (List.Init("key"));
// List.Add
void (List.Add({}));
// List.Retrieve
void (List.Retrieve({}));
// List.Remove
void (_list.Remove());
// List.Subscribers.Add
void (_listSubscribers.Add({}));
// List.Subscribers.Retrieve
void (_listSubscribers.Retrieve());
// List.Subscribers.Unsubscribe
void (_listSubscribers.Unsubscribe("emailAddress"));
// List.Subscribers.Update
void (_listSubscribers.Update("emailAddress", "status"));
// List.Subscribers.Upsert
void (_listSubscribers.Upsert("emailAddress", {}));
// List.Subscribers.Tracking.Retrieve
void (_listSubTracking.Retrieve({}));
// Subscriber.Init
void (Subscriber.Init("key"));
// Subscriber.Add
void (Subscriber.Add({}));
// Subscriber.Retrieve
void (Subscriber.Retrieve({}));
// Subscriber.Upsert
void (_subscriber.Upsert({}));
// Subscriber.Statistics
void (_subscriber.Statistics());
// Subscriber.Update
void (_subscriber.Update({}));
// Subscriber.Remove
void (_subscriber.Remove());
// Subscriber.Unsubscribe
void (_subscriber.Unsubscribe());
// Subscriber.Attributes.Retrieve
void (_subscriberAttrs.Retrieve());
// Subscriber.Lists.Retrieve
void (_subscriberLists.Retrieve());
// Email.Init
void (Email.Init("key"));
// Email.Add
void (Email.Add({}));
// Email.Retrieve
void (Email.Retrieve({}));
// Email.Update
void (_email.Update({}));
// Email.Remove
void (_email.Remove());
// Email.Validate
void (_email.Validate());
// Email.CheckContent
void (_email.CheckContent());
// Send.Init
void (Send.Init(1));
// Send.Add
void (Send.Add("emailKey", []));
// Send.Retrieve
void (Send.Retrieve({}));
// Send.RetrieveLists
void (Send.RetrieveLists({}));
// Send.Remove
void (_send.Remove());
// Send.CancelSend
void (_send.CancelSend());
// Send.Tracking.Retrieve
void (Send.Tracking.Retrieve({}));
// Send.Definition.Init
void (Send.Definition.Init("key"));
// Send.Definition.Add
void (Send.Definition.Add({}, "sendClassificationKey", "emailKey", []));
// Send.Definition.AddWithDE
void (Send.Definition.AddWithDE({}, "sendClassificationKey", "emailKey", "sendableDataExtensionKey", "publicationListKey"));
// Send.Definition.AddWithFilterDefinition
void (Send.Definition.AddWithFilterDefinition({}, "sendClassificationKey", "emailKey", "filterDefinitionKey", 1));
// Send.Definition.Retrieve
void (Send.Definition.Retrieve());
// Send.Definition.Update
void (_sendDef.Update({}));
// Send.Definition.Remove
void (_sendDef.Remove());
// Send.Definition.Send
void (_sendDef.Send());
// TriggeredSend.Init
void (TriggeredSend.Init("key"));
// TriggeredSend.Add
void (TriggeredSend.Add({}));
// TriggeredSend.Retrieve
void (TriggeredSend.Retrieve({}));
// TriggeredSend.Update
void (_triggeredSend.Update({}));
// TriggeredSend.Start
void (_triggeredSend.Start());
// TriggeredSend.Pause
void (_triggeredSend.Pause());
// TriggeredSend.Publish
void (_triggeredSend.Publish());
// TriggeredSend.Send
void (_triggeredSend.Send("emailAddress"));
// TriggeredSend.Tracking.Retrieve
void (_tsTracking.Retrieve());
// TriggeredSend.Tracking.Clicks.Retrieve
void (_tsClicks.Retrieve({}));
// TriggeredSend.Tracking.TotalByInterval.Retrieve
void (_tsInterval.Retrieve("type", "startDate", "endDate", "groupBy"));

// ── Events ──
// BounceEvent.Retrieve
void (BounceEvent.Retrieve({}));
// ClickEvent.Retrieve
void (ClickEvent.Retrieve({}));
// ForwardedEmailEvent.Retrieve
void (ForwardedEmailEvent.Retrieve({}));
// ForwardedEmailOptInEvent.Retrieve
void (ForwardedEmailOptInEvent.Retrieve({}));
// NotSentEvent.Retrieve
void (NotSentEvent.Retrieve({}));
// OpenEvent.Retrieve
void (OpenEvent.Retrieve({}));
// SentEvent.Retrieve
void (SentEvent.Retrieve({}));
// SurveyEvent.Retrieve
void (SurveyEvent.Retrieve({}));
// UnsubEvent.Retrieve
void (UnsubEvent.Retrieve({}));

// ── ECMAScript ──
// Array.prototype.join
void (_arr.join());
// Array.prototype.push
void (_arr.push());
// Array.prototype.pop
void (_arr.pop());
// Array.prototype.shift
void (_arr.shift());
// Array.prototype.unshift
void (_arr.unshift());
// Array.prototype.concat
void (_arr.concat());
// Array.prototype.slice
void (_arr.slice());
// Array.prototype.sort
void (_arr.sort());
// Array.prototype.reverse
void (_arr.reverse());
// Array.prototype.length
void (_arr.length);
// Array.prototype.toLocaleString
void (_arr.toLocaleString());
// String.prototype.charAt
void (_str.charAt());
// String.prototype.charCodeAt
void (_str.charCodeAt());
// String.prototype.indexOf
void (_str.indexOf());
// String.prototype.lastIndexOf
void (_str.lastIndexOf());
// String.prototype.match
void (_str.match());
// String.prototype.replace
void (_str.replace());
// String.prototype.search
void (_str.search());
// String.prototype.slice
void (_str.slice());
// String.prototype.split
void (_str.split());
// String.prototype.substring
void (_str.substring());
// String.prototype.toLowerCase
void (_str.toLowerCase());
// String.prototype.toLocaleLowerCase
void (_str.toLocaleLowerCase());
// String.prototype.toUpperCase
void (_str.toUpperCase());
// String.prototype.concat
void (_str.concat());
// String.prototype.localeCompare
void (_str.localeCompare());
// String.prototype.length
void (_str.length);
// Math.abs
void (Math.abs());
// Math.ceil
void (Math.ceil());
// Math.floor
void (Math.floor());
// Math.max
void (Math.max());
// Math.min
void (Math.min());
// Math.pow
void (Math.pow());
// Math.random
void (Math.random());
// Math.round
void (Math.round());
// Math.sqrt
void (Math.sqrt());
// Math.sin
void (Math.sin());
// Math.cos
void (Math.cos());
// Math.tan
void (Math.tan());
// Math.asin
void (Math.asin());
// Math.acos
void (Math.acos());
// Math.atan
void (Math.atan());
// Math.atan2
void (Math.atan2());
// Math.exp
void (Math.exp());
// Math.log
void (Math.log());
// Math.PI
void (Math.PI);
// Math.E
void (Math.E);
// Math.LN2
void (Math.LN2);
// Math.LN10
void (Math.LN10);
// Math.LOG2E
void (Math.LOG2E);
// Math.SQRT2
void (Math.SQRT2);
// Math.SQRT1_2
void (Math.SQRT1_2);
// Number.prototype.toFixed
void (_num.toFixed());
// Number.prototype.toExponential
void (_num.toExponential());
// Number.prototype.toPrecision
void (_num.toPrecision());
// Number.prototype.toString
void (_num.toString());
// Number.prototype.valueOf
void (_num.valueOf());
// Object.prototype.hasOwnProperty
void (_obj.hasOwnProperty());
// Object.prototype.toString
void (_obj.toString());
// Object.prototype.valueOf
void (_obj.valueOf());
// Global.parseInt
void (parseInt());
// Global.parseFloat
void (parseFloat());
// Global.isNaN
void (isNaN());
// Global.isFinite
void (isFinite());
// Global.eval
void (eval());
// Global.RegExp
void (RegExp("pattern"));
// RegExp.test
void (_re.test("string"));
// RegExp.exec
void (_re.exec("string"));
// RegExp.source
void (_re.source);
// RegExp.global
void (_re.global);
// RegExp.lastIndex
void (_re.lastIndex);
// Date.prototype.getFullYear
void (_date.getFullYear());
// Date.prototype.getMonth
void (_date.getMonth());
// Date.prototype.getDate
void (_date.getDate());
// Date.prototype.getHours
void (_date.getHours());
// Date.prototype.getTime
void (_date.getTime());
// Date.prototype.getTimezoneOffset
void (_date.getTimezoneOffset());
// Date.prototype.getMinutes
void (_date.getMinutes());
// Date.prototype.getSeconds
void (_date.getSeconds());
// Date.prototype.getDay
void (_date.getDay());
// Date.prototype.getMilliseconds
void (_date.getMilliseconds());
// Date.prototype.toString
void (_date.toString());
// Date.prototype.toDateString
void (_date.toDateString());
// Date.prototype.toUTCString
void (_date.toUTCString());
// Date.prototype.valueOf
void (_date.valueOf());
// Date.prototype.getUTCFullYear
void (_date.getUTCFullYear());
// Date.prototype.getUTCMonth
void (_date.getUTCMonth());
// Date.prototype.getUTCDate
void (_date.getUTCDate());
// Date.prototype.getUTCDay
void (_date.getUTCDay());
// Date.prototype.getUTCHours
void (_date.getUTCHours());
// Date.prototype.getUTCMinutes
void (_date.getUTCMinutes());
// Date.prototype.getUTCSeconds
void (_date.getUTCSeconds());
// Date.prototype.getUTCMilliseconds
void (_date.getUTCMilliseconds());
// Date.prototype.toTimeString
void (_date.toTimeString());
// Date.UTC
void (Date.UTC());
// Date.parse
void (Date.parse());
// Date.now
void (Date.now());
// Object.defineProperty
void (Object.defineProperty());
// Object.getPrototypeOf
void (Object.getPrototypeOf());
// Function.prototype.call
void (Function.prototype.call({}));
// Function.prototype.apply
void (Function.prototype.apply({}));
// Function.prototype.toString
void (Function.prototype.toString());

// ── SSJS Global ──
// String
void (String());
// Error
void (new Error());
// Base64Encode
void (Base64Encode("string"));
// Base64Decode
void (Base64Decode("encodedString"));
// ContentArea
void (ContentArea(1));
// ContentAreaByName
void (ContentAreaByName("name"));

// ── SSJS Global Alias ──
// BeginImpressionRegion (alias of Platform.Function.BeginImpressionRegion)
void (BeginImpressionRegion("name"));
// EndImpressionRegion (alias of Platform.Function.EndImpressionRegion)
void (EndImpressionRegion());
// Now (alias of Platform.Function.Now)
void (Now());

// ── SSJS Global ──
// Redirect
void (Redirect("url", true));

// ── SSJS Global Alias ──
// GUID (alias of Platform.Function.GUID)
void (GUID());
// IsEmailAddress (alias of Platform.Function.IsEmailAddress)
void (IsEmailAddress("value"));
// IsPhoneNumber (alias of Platform.Function.IsPhoneNumber)
void (IsPhoneNumber("value"));

// ── SSJS Global ──
// Write
void (Write("text"));
// Stringify
void (Stringify({}));
// Format
void (Format("textToFormat", "formatCode"));

// =============================================================================
// KNOWN GAPS — documented in ssjs.guide but NOT catalogued in ssjs-data
// Use this block to confirm TypeScript / IntelliSense gaps (e.g. RegExp).
// =============================================================================

// RegExp — ssjs.guide/language/regular-expressions.md
var _reCtor = new RegExp("pattern", "i");
void (_reCtor.test("sample"));
void (_reCtor.exec("sample"));
void (_str.match(_reCtor));

// Native constructors — ssjs.guide/engine-limitations/known-bugs.md
var _dateCtor = new Date();
var _arrCtor = new Array(3);
var _objCtor = new Object();
